# pyproject.toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "unisched"
version = "0.1.0"
description = "An exam scheduler application built with Python, designed to efficiently manage and optimize exam schedules at university level."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = ["pyside6==6.6"]

[project.scripts]
unisched = "unisched.__main__:main"

[project.optional-dependencies]
deploy = ["nuitka", "zstandard"]  # deployment-only deps

[tool.hatch.build.targets.wheel]
packages = ["src/unisched"]
