# pyproject.toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "unisched"
version = "0.2.0"
description = "An exam scheduler application built with Python, designed to optimize exam schedules at university level."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "odfpy>=1.4.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "pyside6>=6.7,<6.8",
]
authors = [
    { name = "Adheesh Trivedi", email = "adheeshtrivedi@gmail.com" }
]

[project.scripts]
unisched = "unisched.__main__:main"

[project.optional-dependencies]
dev = ["black", "pytest", "pytest-qt"]  # development-only deps
example = ["tqdm"]  # example-only deps

[tool.hatch.build]
include = [
  "/src",
  "/README.md",
  "/LICENSE",
  "/public"
]

[tool.hatch.build.targets.wheel]
packages = ["src/unisched"]

[tool.black]
line-length = 100
target-version = ['py312']
skip-string-normalization = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-ra"
markers = []
